# File: azure-template-tox-job.yml
# Date: 8-Jul-2019 jdw split out from original pipeline
# Supports: fixtures=mongodb (linux)
#
# Updates:
#  6-Aug-2019  jdw build source and binary wheels by default.
# 13-Aug-2019  jdw export config support token prior to launching tox runner
#
##
parameters:
  tox: ""
  python: ""
  os: "linux"
  fixtures: ""

jobs:
  - job: ${{ format('build_test_{0}_{1}', parameters.tox, parameters.os) }}
    timeoutInMinutes: 0
    pool:
      ${{ if eq(parameters.os, 'macos') }}:
        vmImage: "macOS-13"
      ${{ if eq(parameters.os, 'linux') }}:
        vmImage: "ubuntu-22.04"

    variables:
      - group: py-shared-variables
      - name: DECODE_PERCENTS
        value: false

    steps:
      #
      # ensure the required Python versions are available
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{ parameters.python }}
          addToPath: true
        displayName: setup python
      #
      - checkout: self
        submodules: true
      #
      - ${{ if startsWith(parameters.os, 'macos') }}:
          - bash: |
              set -e
              ls -la /Applications/Xcode*
              sudo xcode-select --switch /Applications/Xcode_12.2.app/Contents/Developer
              which g++
              c++ --version
            displayName: "setup Xcode"
          #
          - script: which brew
            displayName: "Check package manager"
          - script: brew install flex
            displayName: "Install flex"
          - script: which flex
            displayName: "Check flex"
          - script: brew install bison
            displayName: "Install bison"
          - script: which bison
            displayName: "Check bison"
          - script: brew install mariadb
            displayName: "Install mariadb"
      # ----------------------------------------------
      - ${{ if startsWith(parameters.os, 'linux') }}:
          - script: lsb_release -a
            displayName: "Ubuntu kernel version"
          - script: which apt
            displayName: "Installing OS dependencies"
          - script: apt-cache policy | grep http | awk '{print $2 $3}' | sort -u
            displayName: "Checking for repos"
          #
          - script: sudo apt-get update
            displayName: "update apt"
          #- script: sudo apt-get upgrade
          #  displayName: 'upgrade apt'
          #- script: sudo apt-get update
          #  displayName: 'update apt'
          - script: sudo apt-get install flex
            displayName: "Install flex"
          - script: sudo apt-get install bison
            displayName: "Install bison"
      #
        # -----
      - ? ${{ if and(contains(parameters.fixtures, 'mongodb'), startsWith(parameters.os, 'linux')) }}
        : # Mongo install
          - script: |
              sudo apt-get install gnupg wget
              wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -
              # sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
              sudo apt list --installed | grep mongodb
              echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
              # echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
              sudo apt-get update
              sudo apt-get install -y mongodb-org
              sudo apt list --installed | grep mongo
            displayName: "Installing mongodb"
          #
          - script: |
              sudo service mongod start
              sudo ss -tulpn
            displayName: "Start Mongo service"
        #
      #
      - script: 'python -c "import sys; print(sys.version); print(sys.executable)"'
        displayName: show python information
      #
      - script: python -m pip install --upgrade pip
        displayName: "Upgrade pip"
      #
      - script: pip install tox jsonschema 'rcsb.utils.chemref>=0.91' 'jsondiff>=1.2.0'
        displayName: "Install test requirements"
        #
      - script: pip install -r requirements.txt
        displayName: "Install dependencies"
      #
      - ${{ if startsWith(parameters.tox, 'py') }}:
          - script: |
              export CONFIG_SUPPORT_TOKEN_ENV=$(VAR_CONFIG_SUPPORT_TOKEN_ENV)
              ${{ format('python -m tox -e {0}', parameters.tox) }}
            displayName: "Running tox task"
      - ? ${{ if and(not(startsWith(parameters.tox, 'py')), startsWith(parameters.python, '3.10')) }}
        : - script: |
              export CONFIG_SUPPORT_TOKEN_ENV=$(VAR_CONFIG_SUPPORT_TOKEN_ENV)
              ${{ format('python -m tox -e {0}-py310', parameters.tox) }}
            displayName: "Running tox task"
      - ? ${{ if and(not(startsWith(parameters.tox, 'py')), startsWith(parameters.python, '3.9')) }}
        : - script: |
              export CONFIG_SUPPORT_TOKEN_ENV=$(VAR_CONFIG_SUPPORT_TOKEN_ENV)
              ${{ format('python -m tox -e {0}-py39', parameters.tox) }}
            displayName: "Running tox task"
      #
      #  Build artifacts if this is a test target (i.e. labeled as py##)
      #
      - ${{ if startsWith(parameters.tox, 'py') }}:
          - script: pip install --upgrade pip twine setuptools wheel
            displayName: "Acquire build tools"
          - script: python setup.py  sdist --dist-dir "$(System.DefaultWorkingDirectory)/dist"
            displayName: "Build source dist"
          - script: python setup.py  bdist_wheel --dist-dir "$(System.DefaultWorkingDirectory)/dist"
            displayName: "Build wheel"
          #
          - script: python setup.py  sdist --dist-dir "$(System.DefaultWorkingDirectory)/udist"
            displayName: "Build source dist"
          #
          # Check the install artifacts
          - script: ls -lR "$(System.DefaultWorkingDirectory)/dist" "$(System.DefaultWorkingDirectory)/udist"
            displayName: "Listing of installed software"
          #
          - publish: $(System.DefaultWorkingDirectory)/dist
            artifact: ${{ format('sw_{0}_{1}', parameters.tox, parameters.os) }}
          #
          - publish: $(System.DefaultWorkingDirectory)/udist
            artifact: ${{ format('sw_u_{0}_{1}', parameters.tox, parameters.os) }}
        #
