# File: azure-template-publish-job.yml
#
# Update:
#   8-Jul-2019 jdw split out from original pipeline
#   6-Aug-2019 jdw push source wheels (universal) for linux
#  10-Oct-2024 mjt macos 12->13, ubuntu 20->22
#   2-Dec-2025 dwp publish wheel to PyPI
##
parameters:
  tox: ""
  python: ""
  os: "linux"
  fixtures: ""

jobs:
- job: ${{ format('publish_{0}_{1}', parameters.tox, parameters.os) }}
  pool:
    ${{ if eq(parameters.os, 'macos') }}:
      vmImage: 'macOS-15'
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: 'ubuntu-latest'
  dependsOn:
  - ${{ format('build_test_{0}_{1}', parameters.tox, parameters.os) }}
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  #
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: ${{ parameters.python }}
        addToPath: true
      displayName: setup python
    #
    - download: current
      artifact: ${{ format('sw_{0}_{1}', parameters.tox,  parameters.os) }}
    #
    - script: ls -lR $(Pipeline.Workspace)/${{ format('sw_{0}_{1}', parameters.tox, parameters.os) }}
      displayName: "Listing of downloaded artifacts"
    #
    - script: python -m pip install --upgrade pip twine wheel hatch
      displayName: 'Install packaging tools'
    #
    - task: DownloadSecureFile@1
      name: pypicred
      displayName: 'Download PyPI credentials'
      inputs:
        secureFile: 'PYPIRC-AZURE'
    #
    - ${{ if startsWith(parameters.os, 'linux') }}:
      - script: twine upload --verbose --skip-existing -r pypi  --config-file $(pypicred.secureFilePath) $(Pipeline.Workspace)/${{ format('sw_{0}_{1}', parameters.tox, parameters.os) }}/*
        displayName: "Linux upload sdist and binary wheel to PyPi ..."
        continueOnError: true
