#!/bin/bash
# File: TEST-REPOSCAN-EXEC-MOCK.sh
#
# Test of ScanRepo CLI
#
python ../exec/RepoScanExec.py  --mock  --scan_chem_comp_ref      --working_path ./test-output --scan_data_file_path ./test-output/scan-cc-data.pic --coverage_file_path ./test-output/scan-cc-coverage.json --type_map_file_path ./test-output/scan-cc-type-map.json  --config_path ../data/dbload-setup-example.cfg --config_name DEFAULT --fail_file_list_path ./test-output/scan-failed-cc-path-list.txt  >& ./test-output/LOGCHEMCOMPFULL
python ../exec/RepoScanExec.py  --mock  --scan_bird_chem_comp_ref --working_path ./test-output --scan_data_file_path ./test-output/scan-bird-cc-data.pic --coverage_file_path ./test-output/scan-bird-cc-coverage.json --type_map_file_path ./test-output/scan-bird-cc-type-map.json  --config_path ../data/dbload-setup-example.cfg --config_name DEFAULT --fail_file_list_path ./test-output/scan-failed-bird-cc-path-list.txt  >& ./test-output/LOGBIRDCHEMCOMPFULL
python ../exec/RepoScanExec.py  --mock  --scan_bird_ref           --working_path ./test-output --scan_data_file_path ./test-output/scan-bird-data.pic --coverage_file_path ./test-output/scan-bird-coverage.json --type_map_file_path ./test-output/scan-bird-type-map.json  --config_path ../data/dbload-setup-example.cfg --config_name DEFAULT --fail_file_list_path ./test-output/scan-failed-bird-path-list.txt  >& ./test-output/LOGBIRDFULL
python ../exec/RepoScanExec.py  --mock  --scan_bird_family_ref    --working_path ./test-output --scan_data_file_path ./test-output/scan-bird-family-data.pic --coverage_file_path ./test-output/scan-bird-family-coverage.json --type_map_file_path ./test-output/scan-bird-family-type-map.json  --config_path ../data/dbload-setup-example.cfg --config_name DEFAULT --fail_file_list_path ./test-output/scan-failed-family-path-list.txt  >& ./test-output/LOGBIRDFAMILY
python ../exec/RepoScanExec.py  --mock  --scan_entry_data         --working_path ./test-output --scan_data_file_path ./test-output/scan-entry-data.pic --coverage_file_path ./test-output/scan-entry-coverage.json --type_map_file_path ./test-output/scan-entry-type-map.json  --config_path ../data/dbload-setup-example.cfg --config_name DEFAULT --fail_file_list_path ./test-output/scan-failed-entry-path-list.txt >& ./test-output/LOGENTRYFULL
#
